Repository MetLife/SSLChecker, pull requests merged in 2020-04, with the labels that each got.

#1 Updated README.md with Authentication guidance
  README.md
Labels: documentation

#2 Removed internal tests
  README.md
  tests/test_SSLChecker.py
Labels: bug

#4 Fixed Microsoft link in README.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#6 v1.01
  CHANGELOG.md
  README.md
  SSLChecker/SSLChecker/__init__.py
  SSLChecker/SSLChecker/function.json
  SSLChecker/sharedcode/scanner.py
  tests/test_SSLChecker.py
Labels: enhancement

#9 Fixed automated tests
  CHANGELOG.md
  README.md
  SSLChecker/SSLChecker/__init__.py
  tests/test_SSLChecker.py
Labels: bug

#11 Develop
  .gitignore
  SSLChecker/SSLChecker/__init__.py
  SSLChecker/SSLChecker/function.json
  SSLChecker/SSLChecker/main.py
  SSLChecker/requirements.txt
  SSLChecker/sharedcode/errors.py
  SSLChecker/sharedcode/logger.py
  SSLChecker/sharedcode/scanner.py
  SSLChecker/sharedcode/shared_dns.py
  tests/test_SSLChecker.py
Labels: enhancement
